import { Organization } from './types';

export const organizations: Organization[] = [
  {
    id: 'ORG-001',
    name: 'Tech Store Egypt',
    email: 'contact@techstore.eg',
    phone: '+20 100 111 2222',
    address: 'Nasr City, Cairo, Egypt',
    status: 'active',
    apiKey: 'tws_live_abc123xyz789',
    webhookUrl: 'https://techstore.eg/api/webhooks/tawsila',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'ORG-002',
    name: 'Electronics Hub',
    email: 'info@electronichub.com',
    phone: '+20 101 333 4444',
    address: 'Maadi, Cairo, Egypt',
    status: 'active',
    apiKey: 'tws_live_def456uvw012',
    webhookUrl: 'https://electronichub.com/webhooks',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'ORG-003',
    name: 'Mobile World',
    email: 'support@mobileworld.eg',
    phone: '+20 122 555 6666',
    address: 'Heliopolis, Cairo, Egypt',
    status: 'active',
    apiKey: 'tws_live_ghi789rst345',
    createdAt: new Date('2024-01-25'),
  },
  {
    id: 'ORG-004',
    name: 'Gadget Store',
    email: 'hello@gadgetstore.eg',
    phone: '+20 106 777 8888',
    address: 'Zamalek, Cairo, Egypt',
    status: 'inactive',
    apiKey: 'tws_live_jkl012mno678',
    webhookUrl: 'https://gadgetstore.eg/api/webhooks',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'ORG-005',
    name: 'Smart Devices Co',
    email: 'info@smartdevices.com',
    phone: '+20 112 999 0000',
    address: 'Dokki, Giza, Egypt',
    status: 'active',
    apiKey: 'tws_live_pqr345stu901',
    webhookUrl: 'https://smartdevices.com/api/tawsila',
    createdAt: new Date('2024-02-05'),
  },
];

