import { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    nameAr: 'سماعات بلوتوث لاسلكية',
    sku: 'WBH-001',
    category: 'Electronics',
    quantity: 45,
    minStock: 10,
    price: 2500,
    image: '/products/headphones.jpg',
    lastUpdated: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Smart Watch Series 5',
    nameAr: 'ساعة ذكية سلسلة 5',
    sku: 'SW-005',
    category: 'Electronics',
    quantity: 8,
    minStock: 15,
    price: 9500,
    image: '/products/smartwatch.jpg',
    lastUpdated: new Date('2024-01-18'),
  },
  {
    id: '3',
    name: 'Portable Phone Charger 20000mAh',
    nameAr: 'شاحن محمول للهاتف 20000 مللي أمبير',
    sku: 'PPC-200',
    category: 'Accessories',
    quantity: 120,
    minStock: 30,
    price: 1200,
    image: '/products/charger.jpg',
    lastUpdated: new Date('2024-01-20'),
  },
  {
    id: '4',
    name: 'USB-C Cable 2m',
    nameAr: 'كابل USB-C بطول 2 متر',
    sku: 'USBC-2M',
    category: 'Accessories',
    quantity: 0,
    minStock: 50,
    price: 450,
    image: '/products/cable.jpg',
    lastUpdated: new Date('2024-01-22'),
  },
  {
    id: '5',
    name: 'Laptop Stand Adjustable',
    nameAr: 'حامل لابتوب قابل للتعديل',
    sku: 'LSA-001',
    category: 'Accessories',
    quantity: 65,
    minStock: 20,
    price: 1600,
    image: '/products/stand.jpg',
    lastUpdated: new Date('2024-01-25'),
  },
  {
    id: '6',
    name: 'Wireless Mouse',
    nameAr: 'ماوس لاسلكي',
    sku: 'WM-100',
    category: 'Electronics',
    quantity: 90,
    minStock: 25,
    price: 850,
    image: '/products/mouse.jpg',
    lastUpdated: new Date('2024-01-28'),
  },
  {
    id: '7',
    name: 'Mechanical Keyboard RGB',
    nameAr: 'لوحة مفاتيح ميكانيكية RGB',
    sku: 'MKR-001',
    category: 'Electronics',
    quantity: 35,
    minStock: 15,
    price: 4200,
    image: '/products/keyboard.jpg',
    lastUpdated: new Date('2024-02-01'),
  },
  {
    id: '8',
    name: 'Webcam 1080p',
    nameAr: 'كاميرا ويب 1080 بكسل',
    sku: 'WC-1080',
    category: 'Electronics',
    quantity: 18,
    minStock: 10,
    price: 1900,
    image: '/products/webcam.jpg',
    lastUpdated: new Date('2024-02-03'),
  },
];
